### ISSUE TITLE
Turn off GOYP notifications

### ISSUE THREAD

**Issue by iexos** [Alikaraki95/Getoffyourphone#30]
Another feature request :)

I do not want to get notifications from this app. The starting notification is superfluous, because I know that I just started it. And the ending notification is saying "Hey look, all these apps you shouldnt use all the time are accessible again!". Maybe its a matter of what you are trying to achieve which this app, but I would like to reduce overall usage aside from complete absense.

**Comment by Alikaraki95** [comment]
The reason i included these features was to inform the users about the settings they selected, in case they just forgot about them ( That's why you can dismiss them and they're not ongoing )

However i'll keep that in mind :) Will add it to the new settings screen. I'm making a new settings screen that will include (for now) the following:

- App Theme (Dark/Lite)
- Block Notifications from locked apps
- Show/Hide notifications from GOYP
- {To Bi Filled Later}

**Comment by Alikaraki95** [comment]
@iexos 

Feature Completed - Will be in upcoming v6.2r

Thanks!
