### ISSUE TITLE
Add action bar Hamburger icon to show right side drawer better.

### ISSUE THREAD

**Issue by Alikaraki95** [Alikaraki95/Getoffyourphone#35]
Currently it's not straight-forward that there's a right side drawer. Need to bring back action bar or give information on first installation that there's a drawer.

**Comment by Avispa** [comment]
Yupp, same here: spend 5 minutes wondering why the lock button is not wokring. First tried to swipe arround, then tryied classic combinations like holding the *overview* button to find the settings, till finally came up with the idea to try the left drawer (harder); because It's a stupid phone with bend edges which doesn't go well with the screen protector.

**Comment by Alikaraki95** [comment]
@Avispa Yeah, sorry about that. It was there, but when i fixed the Dark Theme i forgot to add it back. I'll try and do it in the next version :)

**Comment by Alikaraki95** [comment]
- Fixed

Done: Changed home-screen text to better show that there is a drawer on the left side. I thought adding an action bar would just make it ugly since it will be empty.
